# Use OpenJDK 11 base image from the Docker Hub
FROM openjdk:11-jre-slim

# Set the working directory inside the container
WORKDIR /app

# Copy the JAR file into the container at /app
COPY target/app.jar /app/

# Command to run the application
ENTRYPOINT ["java", "-jar", "/app/app.jar"]
