version: "3.8"

services:
  app:
    build: .
    ports:
      - "8080:8080"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:oracle:thin:@db:1521/XE
      - SPRING_DATASOURCE_USERNAME=user
      - SPRING_DATASOURCE_PASSWORD=pass
    depends_on:
      - db

  db:
    image: gvenzl/oracle-xe:21-slim
    environment:
      - ORACLE_PASSWORD=oracle
      - APP_USER=user
      - APP_USER_PASSWORD=pass
    ports:
      - "1521:1521"
    healthcheck:
      test: ["CMD", "sqlplus", "-S", "/nolog"]
      interval: 30s
      timeout: 10s
      retries: 3
